apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: portal-inspire
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # root
  MYSQL_PASSWORD: cGFzc3dvcmQ= # password
  MYSQL_USER: YWxiZXJ0 # albert
  MYSQL_DATABASE: cG9ydGFsX2luc3BpcmU= # portal_inspire 
