apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: portal-inspire
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: portal-inspire
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
