apiVersion: v1
kind: PersistentVolume
metadata:
  name: codeigniter-pv
  namespace: portal-inspire
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/codeigniter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeigniter-pvc
  namespace: portal-inspire
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
