apiVersion: apps/v1
kind: Deployment
metadata:
  name: portalinspire-mock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codeigniter
  template:
    metadata:
      labels:
        app: codeigniter
    spec:
      containers:
        - name: codeigniter
          image: portalinspiremock.azurecr.io/skripsi-mock-portal-inspire-k8s-codeigniter:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "mysql-service"  # MySQL service name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: codeigniter
spec:
  selector:
    app: codeigniter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
