# php-fpm deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
        - name: php-fpm
          image: portalinspiremock.azurecr.io/skripsi-mock-portal-inspire-k8s-php-fpm:latest
          ports:
            - containerPort: 9000
      imagePullSecrets:
        - name: acr-secret

---
# php-fpm service (for nginx to access)
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
spec:
  selector:
    app: php-fpm
  ports:
    - protocol: TCP
      port: 9000   # PHP-FPM port
      targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: portalinspiremock.azurecr.io/skripsi-mock-portal-inspire-k8s-nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf   # Mount ConfigMap file to a specific path
              subPath: default.conf                      # Ensure it's treated as a file
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config   # This refers to the nginx-config ConfigMap
            items:
              - key: default.conf  # Key in the ConfigMap
                path: default.conf  # The file path to mount in the container
      imagePullSecrets:
        - name: acr-secret

---
# Nginx ConfigMap (to handle PHP-FPM upstream)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream php-fpm {
        server php-fpm:9000;  # Refers to php-fpm service defined earlier
    }

    server {
        listen 80;

        location / {
            fastcgi_pass php-fpm;
            fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
            include fastcgi_params;
        }
    }
